### PR TITLE
Remove NLog and create a simple ILogger implementation

### PR DESCRIPTION
**Pull request by ricaun**
I like to use NLog in some projects but others do not work very well.

I create a simple Logger implementation to remove the NLog dependence in the [NetOctree](https://github.com/mcserep/NetOctree) solution.

### CODE REVIEW

**Comment by mcserep** [comment]
Hi @ricaun,

Thanks for the contribution, but I don't get where would NLog should "not work well"?
NLog is a widely used logging library, because it is robust and can be easily configured with various rules and logging targets to be suitable in different scenarios.

While logging is not a crucial part of this octree library, as error and warning messages are only for debugging purposes, replacing it with a solution where one has to implement their own logging class seems unrequired extra work for me, when there is a completely suitable and widely used, well-known library for that.

So can you specify what issues you have with NLog?

**Comment by ricaun** [comment]
Yes, it's a great idea to use NLog to debug and stuff. 

My point is that If I want to use this package I need to add the NLog in my project too, using or not the NLog package is there in the solution.

And sometimes an unnecessary package could break the whole solution, that's my case 😅. I'm trying to use the package to run in an extension/plugin and adding extra dll always causes problems on the main program.

I actually created my own version like this PR, to make run smooth.

I do not know what would be the best approach. 

In the end, I still need an alternative version anyway. 

In my case, I need to use double instead of float.

**Comment by mcserep** [comment]
I see your point that NLog might be an unnecessary dependency in production, maybe those few log statements could be replaced with the usage of the plain old `System.Diagnostics.Debug` instead. I will think about it.
(Although since NLog is a .NET Standard project with quite standard dependencies, it shouldn't really break your programs. Something smells there 😄  )

**Comment by mcserep** [comment]
> In my case, I need to use double instead of float.

We already have an ongoing discussion on the topic of supporting doubles (see #4); however it turned out it is not that easy to implement without large code redundancy and without hindering performance.

**Comment by ricaun** [comment]
> I see your point that NLog might be an unnecessary dependency in production, maybe those few log statements could be replaced with the usage of the plain old `System.Diagnostics.Debug` instead. I will think about it.
> (Although since NLog is a .NET Standard project with quite standard dependencies, it shouldn't really break your programs. Something smells there 😄 )

`System.Diagnostics.Debug`  could work but I'm not sure if gonna pass to the end user that is using the library. The [Conditional("DEBUG")] is ignored by the compiler I supposed.

> We already have an ongoing discussion on the topic of supporting doubles (see #4); however it turned out it is not that easy to implement without large code redundancy and without hindering performance.

I'm using this package [System.DoubleNumerics](https://www.nuget.org/packages/System.DoubleNumerics) which is basically the `System.Numerics` using double. I'm coding for CAD software so everything uses double by default, double precision is the key in this case. 

A new NetOctreeDouble package could make sense, I probably gonna create one after you decide to remove NLog 😆

**Comment by mcserep** [comment]
I have checked the codebase and there are only a few log messages:
- Most of them are errors, which shouldn't really occur. I think they were just added for debugging purposes during development of the original library. Exception could be thrown instead.
- There is a single warning message, if the params of the octree construction are incorrect. Again, exception could be thrown instead.

These logging messages were already present in the original codebase I forked from (https://github.com/Nition/UnityOctree), but I think they could be removed and replaced with exceptions. This would also solve your issue. I will implement this in the near future.

**Comment by mcserep** [comment]
Regarding the double support, if this mentioned `System.DoubleNumerics` has the same API as the classic `System.Numerics` (and they promise so), then we could use T4 templates or Source Generators (as @sqeezy suggested in #4) to generate both float and double classes, without code redundancy in this package.

**Comment by mcserep** [comment]
Removed the NLog dependency in v2.1.0. In cases when an error occurs (most likely incorrect arguments), an exception is thrown now, instead of fixing the arguments and logging a message.

**Pull request closed without merging**
